In [1]:
import sys


# I hate Python
sys.path.insert(0, "../")

In [2]:
from src.api.barrels import Barrel


barrels: list[Barrel] = [Barrel.dummy(), Barrel.dummy(), Barrel.dummy()]
barrels

[Barrel(sku='NOTHING', ml_per_barrel=0, potion_type=[], price=0, quantity=0),
 Barrel(sku='NOTHING', ml_per_barrel=0, potion_type=[], price=0, quantity=0),
 Barrel(sku='NOTHING', ml_per_barrel=0, potion_type=[], price=0, quantity=0)]

In [3]:
for barrel in barrels:
    barrel.quantity = 1

barrels

[Barrel(sku='NOTHING', ml_per_barrel=0, potion_type=[], price=0, quantity=1),
 Barrel(sku='NOTHING', ml_per_barrel=0, potion_type=[], price=0, quantity=1),
 Barrel(sku='NOTHING', ml_per_barrel=0, potion_type=[], price=0, quantity=1)]

In [8]:
import sqlalchemy
import src.database as db

with db.engine.begin() as connection:
    result = connection.execute(sqlalchemy.text("SELECT * FROM CartItems"))
    #print(result.fetchall())

row = result.first()
row

ProgrammingError: (psycopg2.errors.UndefinedTable) relation "cartitems" does not exist
LINE 1: SELECT * FROM CartItems
                      ^

[SQL: SELECT * FROM CartItems]
(Background on this error at: https://sqlalche.me/e/20/f405)

In [7]:
row[0:1][0]

UUID('0e902dd5-7b45-4ff9-8067-e23f464a7055')

In [33]:
dir(result)

['__annotations__',
 '__class__',
 '__class_getitem__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__enter__',
 '__eq__',
 '__exit__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__next__',
 '__orig_bases__',
 '__parameters__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__slots__',
 '__str__',
 '__subclasshook__',
 '_allrows',
 '_assert_no_memoizations',
 '_attributes',
 '_column_slices',
 '_echo',
 '_fetchall_impl',
 '_fetchiter_impl',
 '_fetchmany_impl',
 '_fetchone_impl',
 '_generate',
 '_generate_rows',
 '_getter',
 '_init_metadata',
 '_is_cursor',
 '_is_protocol',
 '_iter_impl',
 '_iterator_getter',
 '_manyrow_getter',
 '_memoized_keys',
 '_metadata',
 '_next_impl',
 '_no_result_metadata',
 '_onerow_getter',
 '_only_one_row',
 '_post_creational_filter',
 '_raw_all_rows',
 '_raw_row_

In [34]:
result.fetchall()

ResourceClosedError: This result object is closed.

In [4]:
row_wrapped = db.wrap_result_as_global_inventory(row)

In [5]:
dict(row_wrapped)

{'id_': UUID('0e902dd5-7b45-4ff9-8067-e23f464a7055'),
 'gold': 100,
 'num_green_potions': 0,
 'num_green_ml': 0,
 'num_red_potions': 0,
 'num_red_ml': 0,
 'num_blue_potions': 0,
 'num_blue_ml': 0}

In [6]:
dir(row_wrapped)

['Config',
 '__abstractmethods__',
 '__annotations__',
 '__class__',
 '__class_vars__',
 '__config__',
 '__custom_root_type__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__exclude_fields__',
 '__fields__',
 '__fields_set__',
 '__format__',
 '__ge__',
 '__get_validators__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__include_fields__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__json_encoder__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__post_root_validators__',
 '__pre_root_validators__',
 '__pretty__',
 '__private_attributes__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__repr_args__',
 '__repr_name__',
 '__repr_str__',
 '__rich_repr__',
 '__schema_cache__',
 '__setattr__',
 '__setstate__',
 '__signature__',
 '__sizeof__',
 '__slots__',
 '__str__',
 '__subclasshook__',
 '__try_update_forward_refs__',
 '__validators__',
 '_abc_impl',
 '_calculate_keys',
 '_copy_and_set_values',
 '_decompose_class',
 '_enfo

In [8]:
import uuid

uuid.uuid4()

UUID('9cbec4eb-bb5a-4a64-9f72-7bb5444ccb8b')

In [9]:
uuid.uuid4().int

77773831920177095738919093862580811622

In [13]:
from pydantic import BaseModel, Field

class Cart(BaseModel):
    cart_id: int = Field(default_factory=lambda: uuid.uuid4().int)
    cart_items: dict[str, str] = Field(default={})

cart: Cart = Cart()

In [26]:
number = 2.3837876236372695e+38
formatted_number = f"{number:.0f}"
print(formatted_number)

238378762363726954182122458920645558272


In [19]:
uid = uuid.uuid4()
uid

UUID('e69f4c7f-a514-422e-92e2-948258066c4d')

In [20]:
str(uid)

'e69f4c7f-a514-422e-92e2-948258066c4d'

In [22]:
from uuid import UUID


UUID(str(uid))

UUID('e69f4c7f-a514-422e-92e2-948258066c4d')

In [23]:
UUID(str(uid)).int

306549565807233722871571578224128715853

In [24]:
uid.int

306549565807233722871571578224128715853

In [25]:
dc: dict[int, int] = {1: 2, 3: 4, 5: 6}

dc[1]

2

In [40]:
import numpy as np

np.random.randint(10)

1

In [42]:
{k: v for (k, v) in zip(["a", "b", "c"], [1, 2, 3])}

{'a': 1, 'b': 2, 'c': 3}

In [26]:
import numpy as np
from pydantic import BaseModel
import abc


class Schema(BaseModel, abc.ABC):
    @abc.abstractmethod
    def wrap_result(row: tuple):
        pass

    def check_self(self):
        return self.schema()


class TestSchema(Schema):
    upper_bound: int
    
    def wrap_result(row):
        return np.random.randint(30)

#TestSchema.wrap_result("hi")

[None, None, None, None]

In [29]:
class Something(BaseModel):
    a: int
    b: str
    c: float

list(Something.schema()["properties"].keys())

['a', 'b', 'c']

In [11]:
()

()

In [12]:
len(())

0

In [13]:
import numpy as np

arr = np.array([[1, 2], [3, 4]])
arr.sum(axis=1)

array([3, 7])

In [14]:
arr.sum()

10

In [15]:
arr.sum(axis=0)

array([4, 6])

In [16]:
np.argmax([1, 1, 1, 1])

0

In [18]:
from pydantic import BaseModel

class A(BaseModel):
    a: int
    b: float

full_list: list[A] = [A(a=1, b=1.5), A(a=2, b=2.3), A(a=5, b=2.1)]

A(a=1, b=1.5) in full_list

True

In [20]:
np.sum([1, 2, 3, 4])

10

In [21]:
some_class = A(a=1, b=2.0)

some_class.schema()

{'title': 'A',
 'type': 'object',
 'properties': {'a': {'title': 'A', 'type': 'integer'},
  'b': {'title': 'B', 'type': 'number'}},
 'required': ['a', 'b']}

In [27]:
test = TestSchema(upper_bound=1)

In [28]:
test.check_self()

{'title': 'TestSchema',
 'type': 'object',
 'properties': {'upper_bound': {'title': 'Upper Bound', 'type': 'integer'}},
 'required': ['upper_bound']}

In [31]:
list(TestSchema.schema()["properties"].keys())

['upper_bound']

In [35]:
list(test.dict().values())

[1]

In [37]:
import random


random.choice([1, 2, 3, 4])

4

In [50]:
a = np.array([[1, 8], [3, 4]])
np.argmin(a, axis=0)

array([0, 1])

In [51]:
a[0, 0] = 10
a

array([[10,  8],
       [ 3,  4]])

In [53]:
a += 10
a

array([[20, 18],
       [13, 14]])

In [54]:
a > 15

array([[ True,  True],
       [False, False]])

In [56]:
True in (a > 115)

False

In [62]:
import numpy as np

# Generate 3 random numbers
random_numbers = np.random.rand(3) * np.array([True, False, True])

# Normalize them so they sum to 1
probabilities = random_numbers / random_numbers.sum()

print(probabilities)

[0.79082562 0.         0.20917438]


In [64]:
probabilities.astype(bool)

array([ True, False,  True])

In [65]:
np.array([1, -1, 0]).astype(bool)

array([ True,  True, False])